### ISSUE TITLE
Top level statements must precede namespace

### ISSUE THREAD

**Issue by DerekG251** [randycoulman/mix_test_interactive#120] opened 2024-09-22 05:12 UTC
I’m in the process of trying to complete TestInteractive but one error keeps popping saying top level statement must precede namespace and type declarations. What does that mean?

**Comment by randycoulman** [comment] 2024-09-22 05:38
I'm not sure what you mean by "complete TestInteractive". Are you running it from the command line, or calling it from your code? Can you provide more details about what you're trying to do?

Intended usage is from the command line, where you'd run `mix test.interactive` to start the app.

**Comment by randycoulman** [comment] 2024-11-02 23:49
@DerekG251 I'm going to close this issue for now. If this is still a problem for you, feel free to re-open it with additional information to help me understand what the issue is.

**Closed by randycoulman** 2024-11-02 23:49 UTC
